# Generated by Django 3.1.1 on 2020-12-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20201204_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='desciption',
            new_name='description',
        ),
    ]
